services:
  backend:
    build: ./backend
    container_name: biblioteca_backend
    restart: unless-stopped

    environment:
      MONGO_URI: ${MONGO_URI}
      PORT: 3000

    ports:
      - "3000:3000"

networks:
  app-network:
    driver: bridge